# Generated by Django 4.0.3 on 2022-05-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('win_rate', models.IntegerField()),
                ('time_completion', models.TimeField()),
                ('first_try', models.IntegerField()),
                ('second_try', models.IntegerField()),
                ('three_try', models.IntegerField()),
                ('fourth_try', models.IntegerField()),
                ('fifth_try', models.IntegerField()),
                ('sixth_try', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'wordle',
            },
        ),
    ]
