# Generated by Django 4.0.3 on 2022-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordle',
            name='times_played',
            field=models.IntegerField(default=0),
        ),
    ]
