# Generated by Django 4.0.4 on 2022-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_alter_wordle_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordle',
            name='fifth_try',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='first_try',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='fourth_try',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='second_try',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='sixth_try',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='three_try',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='time_completion',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='times_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='win_rate',
            field=models.IntegerField(null=True),
        ),
    ]
