# Generated by Django 4.0.4 on 2022-07-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0009_alter_wordle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordle',
            name='account',
        ),
    ]
