# Generated by Django 4.0.4 on 2022-07-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_account_balls_alter_account_info_and_more'),
        ('wordle', '0012_alter_wordle_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordle',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordle_game', to='accounts.account'),
        ),
    ]
