# Generated by Django 4.0.6 on 2022-09-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_account_profile_pic_alter_account_user'),
        ('wordle', '0015_alter_wordle_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordle',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_game', to='accounts.account'),
        ),
    ]
