# Generated by Django 4.0.3 on 2022-05-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_wordle_times_played'),
        ('minesweeper', '0001_initial'),
        ('balls', '0001_initial'),
        ('sudoku', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balls',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
        ),
        migrations.AddField(
            model_name='account',
            name='minesweeper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
        ),
        migrations.AddField(
            model_name='account',
            name='sudoku',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
        ),
        migrations.AddField(
            model_name='account',
            name='wordle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
        ),
    ]
