# Generated by Django 4.0.4 on 2022-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_balls_account_minesweeper_account_sudoku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
