# Generated by Django 4.0.4 on 2022-06-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0004_alter_wordle_fifth_try_alter_wordle_first_try_and_more'),
        ('minesweeper', '0003_alter_minesweeper_difficulty_alter_minesweeper_time_and_more'),
        ('balls', '0003_alter_balls_score_alter_balls_time'),
        ('sudoku', '0003_alter_sudoku_dificulty_alter_sudoku_time_and_more'),
        ('accounts', '0003_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balls',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
        ),
        migrations.AlterField(
            model_name='account',
            name='minesweeper',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sudoku',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
        ),
        migrations.AlterField(
            model_name='account',
            name='wordle',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
        ),
    ]
