# Generated by Django 4.0.4 on 2022-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_balls_alter_account_minesweeper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
