# Generated by Django 4.0.4 on 2022-06-09 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_info_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_confirm',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(8, 'Password must contain more than 8 characters')]),
        ),
    ]
