# Generated by Django 4.0.4 on 2022-06-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_password_confirm_alter_account_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password_confirm',
        ),
    ]
