# Generated by Django 4.0.4 on 2022-06-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0005_alter_minesweeper_id'),
        ('balls', '0005_alter_balls_id'),
        ('wordle', '0006_alter_wordle_id'),
        ('sudoku', '0005_alter_sudoku_id'),
        ('accounts', '0007_rename_name_account_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balls',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
        ),
        migrations.AlterField(
            model_name='account',
            name='minesweeper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sudoku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
        ),
        migrations.AlterField(
            model_name='account',
            name='wordle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
        ),
    ]
