# Generated by Django 4.0.4 on 2022-06-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0008_alter_sudoku_id'),
        ('minesweeper', '0008_alter_minesweeper_id'),
        ('balls', '0008_alter_balls_id'),
        ('wordle', '0009_alter_wordle_id'),
        ('accounts', '0014_remove_account_balls_remove_account_minesweeper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balls',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='minesweeper',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sudoku',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='wordle',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
            preserve_default=False,
        ),
    ]
