# Generated by Django 4.0.4 on 2022-07-01 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0009_remove_sudoku_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balls', '0009_remove_balls_account'),
        ('wordle', '0010_remove_wordle_account'),
        ('minesweeper', '0009_remove_minesweeper_account'),
        ('accounts', '0017_remove_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balls',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='minesweeper',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sudoku',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='wordle',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
            preserve_default=False,
        ),
    ]
