# Generated by Django 4.0.4 on 2022-07-01 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balls', '0010_balls_account'),
        ('sudoku', '0010_sudoku_account'),
        ('minesweeper', '0010_minesweeper_account'),
        ('wordle', '0011_wordle_account'),
        ('accounts', '0018_account_balls_account_minesweeper_account_sudoku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balls',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
        ),
        migrations.AlterField(
            model_name='account',
            name='minesweeper',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sudoku',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='wordle',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
        ),
    ]
