# Generated by Django 4.0.4 on 2022-07-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0011_alter_sudoku_account'),
        ('wordle', '0012_alter_wordle_account'),
        ('balls', '0011_alter_balls_account'),
        ('minesweeper', '0011_alter_minesweeper_account'),
        ('accounts', '0019_alter_account_balls_alter_account_minesweeper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balls',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
        ),
        migrations.AlterField(
            model_name='account',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='minesweeper',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='sudoku',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
        ),
        migrations.AlterField(
            model_name='account',
            name='wordle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
        ),
    ]
