# Generated by Django 4.0.4 on 2022-07-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0012_alter_minesweeper_account'),
        ('wordle', '0013_alter_wordle_account'),
        ('balls', '0012_alter_balls_account'),
        ('sudoku', '0012_alter_sudoku_account'),
        ('accounts', '0020_alter_account_balls_alter_account_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balls',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='balls.balls'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='minesweeper',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='minesweeper.minesweeper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='sudoku',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='sudoku.sudoku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='wordle',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='wordle.wordle'),
            preserve_default=False,
        ),
    ]
