# Generated by Django 4.0.6 on 2022-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_account_profile_pic_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='info',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='account_images'),
        ),
    ]
