# Generated by Django 4.0.3 on 2022-05-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineSweeper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('win_rate', models.IntegerField()),
                ('time', models.TimeField()),
                ('difficulty', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'minesweeper',
            },
        ),
    ]
