# Generated by Django 4.0.3 on 2022-05-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_balls_account_minesweeper_account_sudoku_and_more'),
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweeper',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minesweeper_game', to='accounts.account'),
        ),
    ]
