# Generated by Django 4.0.4 on 2022-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_alter_minesweeper_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweeper',
            name='difficulty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minesweeper',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='minesweeper',
            name='win_rate',
            field=models.IntegerField(null=True),
        ),
    ]
