# Generated by Django 4.0.4 on 2022-06-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0005_alter_sudoku_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudoku',
            name='account',
        ),
    ]
