# Generated by Django 4.0.3 on 2022-05-27 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8, 'Password must contain more than 8 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
