# Generated by Django 4.0.4 on 2022-06-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balls', '0005_alter_balls_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balls',
            name='account',
        ),
    ]
